{% set name = "geouned" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e3e7bab26290873ffaf8b76d3270bc36413040720bf64fcca5ca629ff51b5d2

build:
  entry_points:
    - geouned_cadtocsg = geouned.GEOUNED.scripts.geouned_cadtocsg:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=69.5.1
    - setuptools-scm >=8.1.0
    - pip
  run:
    - python >=3.8
    - freecad
    - tqdm
    - numpy

test:
  imports:
    - geouned
  requires:
    - pip
    - pytest
  source_files:
    - tests
    - testing
  commands:
    - pip check
    - geouned_cadtocsg --help
    - pytest tests/test_convert.py

about:
  home: https://github.com/GEOUNED-org/GEOUNED
  summary: Conversion tool from CAD to CGS/CGS to CAD for Monte Carlo particle transport codes (OpenMC, Phits, Serpent, MCNP)
  license: EUPL-1.2
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://geouned-org.github.io/GEOUNED/index.html
  dev_url: https://github.com/GEOUNED-org/GEOUNED

extra:
  recipe-maintainers:
    - shimwell
