{% set name = "geouned" %}
{% set version = "1.6.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61a409867597859a316c15de30ff4838827f96f13d2c5522cabe8ccce2e320ec

build:
  entry_points:
    - geouned_cadtocsg = geouned.GEOUNED.scripts.geouned_cadtocsg:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=69.5.1
    - setuptools-scm >=8.1.0
    - pip
  run:
    - python >={{ python_min }}
    - freecad
    - tqdm
    - numpy

test:
  imports:
    - geouned
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
    - testing
  commands:
    - pip check
    - geouned_cadtocsg --help
    - geouned_csgtocad --help
    - pytest tests/test_csgtocad.py
    - pytest tests/test_cadtocsg.py

about:
  home: https://github.com/GEOUNED-org/GEOUNED
  summary: Conversion tool from CAD to CGS/CGS to CAD for Monte Carlo particle transport codes (OpenMC, Phits, Serpent, MCNP)
  license: EUPL-1.2
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://geouned-org.github.io/GEOUNED/index.html
  dev_url: https://github.com/GEOUNED-org/GEOUNED

extra:
  recipe-maintainers:
    - shimwell
    - akolsek
    - AlvaroCubi
